name: Playwright UI Tests

on:
  push:
    branches: [ main, master ] 
  pull_request:
    branches: [ main, master ] # Запуск тестов при создании MR в main или master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: lts/*
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Run Playwright 
      env:
        TEST_EMAIL: ${{ secrets.ENV_EMAIL }}
        TEST_PASSWORD: ${{ secrets.ENV_PASSWORD }}
      run: npx playwright test --project=chromium

    - name: Generate Allure Report
      if: always() # Выполнять генерацию отчета всегда, даже если тесты упали
      run: npm run allure:reporter || true # Игнорируем ошибку генерации, чтобы загрузить то, что успело собраться

    - name: Upload Allure Report Artifact
      if: always() # Сохранять отчет в артефакты всегда
      uses: actions/upload-artifact@v4
      with:
        name: allure-report
        path: allure-report/
        retention-days: 5
